/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-12 at 18:39:39 UTC 
 * Modify at your own risk.
 */

package com.enpoints.frutaendpoint;

/**
 * Service definition for Frutaendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link FrutaendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Frutaendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the frutaendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://id-ios-android.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "frutaendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Frutaendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Frutaendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getFruta".
   *
   * This request holds the parameters needed by the the frutaendpoint server.  After setting any
   * optional parameters, call the {@link GetFruta#execute()} method to invoke the remote operation.
   *
   * @param nombre
   * @return the request
   */
  public GetFruta getFruta(java.lang.String nombre) throws java.io.IOException {
    GetFruta result = new GetFruta(nombre);
    initialize(result);
    return result;
  }

  public class GetFruta extends FrutaendpointRequest<com.enpoints.frutaendpoint.model.Fruta> {

    private static final String REST_PATH = "fruta/{nombre}";

    /**
     * Create a request for the method "getFruta".
     *
     * This request holds the parameters needed by the the frutaendpoint server.  After setting any
     * optional parameters, call the {@link GetFruta#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetFruta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param nombre
     * @since 1.13
     */
    protected GetFruta(java.lang.String nombre) {
      super(Frutaendpoint.this, "GET", REST_PATH, null, com.enpoints.frutaendpoint.model.Fruta.class);
      this.nombre = com.google.api.client.util.Preconditions.checkNotNull(nombre, "Required parameter nombre must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetFruta setAlt(java.lang.String alt) {
      return (GetFruta) super.setAlt(alt);
    }

    @Override
    public GetFruta setFields(java.lang.String fields) {
      return (GetFruta) super.setFields(fields);
    }

    @Override
    public GetFruta setKey(java.lang.String key) {
      return (GetFruta) super.setKey(key);
    }

    @Override
    public GetFruta setOauthToken(java.lang.String oauthToken) {
      return (GetFruta) super.setOauthToken(oauthToken);
    }

    @Override
    public GetFruta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetFruta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetFruta setQuotaUser(java.lang.String quotaUser) {
      return (GetFruta) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetFruta setUserIp(java.lang.String userIp) {
      return (GetFruta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String nombre;

    /**

     */
    public java.lang.String getNombre() {
      return nombre;
    }

    public GetFruta setNombre(java.lang.String nombre) {
      this.nombre = nombre;
      return this;
    }

    @Override
    public GetFruta set(String parameterName, Object value) {
      return (GetFruta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertFruta".
   *
   * This request holds the parameters needed by the the frutaendpoint server.  After setting any
   * optional parameters, call the {@link InsertFruta#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.enpoints.frutaendpoint.model.Fruta}
   * @return the request
   */
  public InsertFruta insertFruta(com.enpoints.frutaendpoint.model.Fruta content) throws java.io.IOException {
    InsertFruta result = new InsertFruta(content);
    initialize(result);
    return result;
  }

  public class InsertFruta extends FrutaendpointRequest<com.enpoints.frutaendpoint.model.Fruta> {

    private static final String REST_PATH = "fruta";

    /**
     * Create a request for the method "insertFruta".
     *
     * This request holds the parameters needed by the the frutaendpoint server.  After setting any
     * optional parameters, call the {@link InsertFruta#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertFruta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.enpoints.frutaendpoint.model.Fruta}
     * @since 1.13
     */
    protected InsertFruta(com.enpoints.frutaendpoint.model.Fruta content) {
      super(Frutaendpoint.this, "POST", REST_PATH, content, com.enpoints.frutaendpoint.model.Fruta.class);
    }

    @Override
    public InsertFruta setAlt(java.lang.String alt) {
      return (InsertFruta) super.setAlt(alt);
    }

    @Override
    public InsertFruta setFields(java.lang.String fields) {
      return (InsertFruta) super.setFields(fields);
    }

    @Override
    public InsertFruta setKey(java.lang.String key) {
      return (InsertFruta) super.setKey(key);
    }

    @Override
    public InsertFruta setOauthToken(java.lang.String oauthToken) {
      return (InsertFruta) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertFruta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertFruta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertFruta setQuotaUser(java.lang.String quotaUser) {
      return (InsertFruta) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertFruta setUserIp(java.lang.String userIp) {
      return (InsertFruta) super.setUserIp(userIp);
    }

    @Override
    public InsertFruta set(String parameterName, Object value) {
      return (InsertFruta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listFruta".
   *
   * This request holds the parameters needed by the the frutaendpoint server.  After setting any
   * optional parameters, call the {@link ListFruta#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListFruta listFruta() throws java.io.IOException {
    ListFruta result = new ListFruta();
    initialize(result);
    return result;
  }

  public class ListFruta extends FrutaendpointRequest<com.enpoints.frutaendpoint.model.CollectionResponseFruta> {

    private static final String REST_PATH = "fruta";

    /**
     * Create a request for the method "listFruta".
     *
     * This request holds the parameters needed by the the frutaendpoint server.  After setting any
     * optional parameters, call the {@link ListFruta#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListFruta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListFruta() {
      super(Frutaendpoint.this, "GET", REST_PATH, null, com.enpoints.frutaendpoint.model.CollectionResponseFruta.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListFruta setAlt(java.lang.String alt) {
      return (ListFruta) super.setAlt(alt);
    }

    @Override
    public ListFruta setFields(java.lang.String fields) {
      return (ListFruta) super.setFields(fields);
    }

    @Override
    public ListFruta setKey(java.lang.String key) {
      return (ListFruta) super.setKey(key);
    }

    @Override
    public ListFruta setOauthToken(java.lang.String oauthToken) {
      return (ListFruta) super.setOauthToken(oauthToken);
    }

    @Override
    public ListFruta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListFruta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListFruta setQuotaUser(java.lang.String quotaUser) {
      return (ListFruta) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListFruta setUserIp(java.lang.String userIp) {
      return (ListFruta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListFruta setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListFruta setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListFruta set(String parameterName, Object value) {
      return (ListFruta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeFruta".
   *
   * This request holds the parameters needed by the the frutaendpoint server.  After setting any
   * optional parameters, call the {@link RemoveFruta#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveFruta removeFruta(java.lang.String id) throws java.io.IOException {
    RemoveFruta result = new RemoveFruta(id);
    initialize(result);
    return result;
  }

  public class RemoveFruta extends FrutaendpointRequest<Void> {

    private static final String REST_PATH = "fruta/{id}";

    /**
     * Create a request for the method "removeFruta".
     *
     * This request holds the parameters needed by the the frutaendpoint server.  After setting any
     * optional parameters, call the {@link RemoveFruta#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveFruta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveFruta(java.lang.String id) {
      super(Frutaendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveFruta setAlt(java.lang.String alt) {
      return (RemoveFruta) super.setAlt(alt);
    }

    @Override
    public RemoveFruta setFields(java.lang.String fields) {
      return (RemoveFruta) super.setFields(fields);
    }

    @Override
    public RemoveFruta setKey(java.lang.String key) {
      return (RemoveFruta) super.setKey(key);
    }

    @Override
    public RemoveFruta setOauthToken(java.lang.String oauthToken) {
      return (RemoveFruta) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveFruta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveFruta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveFruta setQuotaUser(java.lang.String quotaUser) {
      return (RemoveFruta) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveFruta setUserIp(java.lang.String userIp) {
      return (RemoveFruta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveFruta setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveFruta set(String parameterName, Object value) {
      return (RemoveFruta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateFruta".
   *
   * This request holds the parameters needed by the the frutaendpoint server.  After setting any
   * optional parameters, call the {@link UpdateFruta#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.enpoints.frutaendpoint.model.Fruta}
   * @return the request
   */
  public UpdateFruta updateFruta(com.enpoints.frutaendpoint.model.Fruta content) throws java.io.IOException {
    UpdateFruta result = new UpdateFruta(content);
    initialize(result);
    return result;
  }

  public class UpdateFruta extends FrutaendpointRequest<com.enpoints.frutaendpoint.model.Fruta> {

    private static final String REST_PATH = "fruta";

    /**
     * Create a request for the method "updateFruta".
     *
     * This request holds the parameters needed by the the frutaendpoint server.  After setting any
     * optional parameters, call the {@link UpdateFruta#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateFruta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.enpoints.frutaendpoint.model.Fruta}
     * @since 1.13
     */
    protected UpdateFruta(com.enpoints.frutaendpoint.model.Fruta content) {
      super(Frutaendpoint.this, "PUT", REST_PATH, content, com.enpoints.frutaendpoint.model.Fruta.class);
    }

    @Override
    public UpdateFruta setAlt(java.lang.String alt) {
      return (UpdateFruta) super.setAlt(alt);
    }

    @Override
    public UpdateFruta setFields(java.lang.String fields) {
      return (UpdateFruta) super.setFields(fields);
    }

    @Override
    public UpdateFruta setKey(java.lang.String key) {
      return (UpdateFruta) super.setKey(key);
    }

    @Override
    public UpdateFruta setOauthToken(java.lang.String oauthToken) {
      return (UpdateFruta) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateFruta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateFruta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateFruta setQuotaUser(java.lang.String quotaUser) {
      return (UpdateFruta) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateFruta setUserIp(java.lang.String userIp) {
      return (UpdateFruta) super.setUserIp(userIp);
    }

    @Override
    public UpdateFruta set(String parameterName, Object value) {
      return (UpdateFruta) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Frutaendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Frutaendpoint}. */
    @Override
    public Frutaendpoint build() {
      return new Frutaendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link FrutaendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setFrutaendpointRequestInitializer(
        FrutaendpointRequestInitializer frutaendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(frutaendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
